repos:
# - repo: https://github.com/pycqa/isort
#   rev: 5.13.2
#   hooks:
#     - id: isort
#       language_version: python3
#       types: [python]
#       files: ^.*\.py$


-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3
        types: [python]
        files: ^.*\.py$